#!/usr/bin/perl -w

#Takes as input file allSeqs.fas generated by 'cat ../A02_nuclearAssembly/IBAass*/*finalseqs.fasta >allSeqs.fas'
#change  email address on line 70

open FH, "<allSeqs.fas";
open OUT, ">allSeqs.fasta";

while (<FH>)
{
     if (/>(\S+)/)
     {
	 print OUT "\n>$1\n";
     }

     elsif (/(\S+)/)
     {
	 print OUT "$1";
     }
}
print OUT "\n";
close FH;
close OUT;

%locushash = ();

open FH2, "<allSeqs.fasta";

while (<FH2>)
{
    if (/^>(L\d+)\_/)
    {
        $loc = $1;
        if (! exists $locushash{$loc})
        {
            $locushash{$loc} = 1;
        }
    }
}
close FH2;

for $LOC(keys %locushash)
{
    open FH3, "<allSeqs.fasta";
    open OUT2, ">$LOC.fa";
    $ok = 1;
    while (<FH3>)
    {
        if (/^>$LOC\_\S+/)
        {
            print OUT2;
            $ok = 0;
        }
        elsif (/^>\S+/)
        {
            $ok++;
        }
        elsif ((/^\S+/) && ($ok == 0))
        {
            print OUT2;
        }
    }
    close FH3;
    close OUT2;
}


open OUT3, ">MoreMem.sh";
print OUT3 "#!/bin/bash\n";
#Deleted SBATCH lines
print OUT3 "[[ -d \$SLURM_SUBMIT_DIR ]] && cd \$SLURM_SUBMIT_DIR\n";
#Deleted Module load line
print OUT3 "for i in *.fa\n{\n /root/usearch11.0.667_i86linux32 -ublast \$i -db ../ref/\$i -evalue 0.01 -top_hit_only -blast6out \$i\\_probe_hits.txt --strand both -qsegout \$i\\_probeR.fasta\n}\n";
close OUT3;

system "bash MoreMem.sh";


